version: "3"
services:
  shadowsocks:
    image: oddrationale/docker-shadowsocks:latest
    command: -s 0.0.0.0 -p ${SHADOWSOCKS_PORT} -k ${SHADOWSOCKS_PASSWORD} -m ${SHADOWSOCKS_METHOD}
    ports:
      - "${SHADOWSOCKS_PORT}:${SHADOWSOCKS_PORT}"
    container_name: shadowsocks
    restart: always
    networks:
      - default
